services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  backend:
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  mongo:
    ports:
      - "27017:27017"

  neo4j:
    ports:
      - "7474:7474"
      - "7687:7687"

  cassandra:
    ports:
      - "9042:9042"

  redis:
    ports:
      - "6379:6379"

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html

# Cómo lo ejecuto?
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up      - ./nginx.conf:/etc/nginx/nginx.conf:ro