services:
  cassandra:
    image: cassandra:4.1
    restart: always
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TecDigitalitoCluster
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256m
      - JVM_OPTS=-Xms1G -Xmx1G -XX:MaxGCPauseMillis=200
    command: ["cassandra", "-f"]
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pw
      - MONGO_INITDB_DATABASE=tecdigitalito_mongo_db
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.256"]
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  neo4j:
    image: neo4j:5.15-community
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j-pw
    volumes:
      - neo4j-data:/data
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  neo4j-data:
  cassandra-data:
  redis-data:
  mongo-data:

networks:
  app-network: