services:
  backend:
    build:
      context: ./Backend
      dockerfile: ../docker/Dockerfile
      target: backend
    restart: always
    env_file:
      - ./Backend/.env
    depends_on:
      - cassandra
      - mongo
      - neo4j
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  cassandra:
    image: cassandra:latest
    restart: always
    environment:
      - CASSANDRA_CLUSTER_NAME=TecDigitalitoCluster
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - app-network

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=tecdigitalito_mongo_db
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/neo4j-pw
    volumes:
      - neo4j-data:/data
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  neo4j-data:
  cassandra-data:
  redis-data:
  mongo-data:

networks:
  app-network: